name: CI CD - GateKeeper - Test YML

on:
  push:
    branches: [ "patrick-final-testing" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libssl-dev libsqlite3-dev gcc-10 g++-10

      - name: Compile with Coverage
        run: |
          gcc -Wall -Werror -g --coverage -I/usr/local/include -I/opt/local/include \
              -o ptest main.c data_encryption.c user_interface.c database.c app_data.c \
              -L/usr/local/lib -L/usr/lib/x86_64-linux-gnu -lcrypto -lssl -lsqlite3

      - name : Run test_script
        run: |
          chmod +x ./test_script

      - name: Generate Coverage Reports
        run: |
          gcov ptest-main.c > main_coverage.txt
          gcov ptest-data_encryption.c > data_encryption_coverage.txt
          gcov ptest-user_interface.c > user_interface_coverage.txt
          gcov ptest-database.c > database_coverage.txt
          gcov ptest-app_data.c > app_data.txt

      - name: Upload Coverage Reports
        uses: actions/upload-artifact@v4
        with:
          name: Coverage Reports
          path: |
            main_coverage.txt
            data_encryption_coverage.txt
            user_interface_coverage.txt
            database_coverage.txt
            app_data.txt
