name: CI CD - GateKeeper - test YML

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Tests
        run: |
          make ptest
          chmod +x ./test_script > test_results.txt

      - name: Upload Test Results
        uses: actions/upload-artifact@v4 
        with:
          name: Test Results
          path: ./test_results.txt 
